services:
  rest-api:
    build:
      context: ./server/rest-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/rest-api:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CHOKIDAR_USEPOLLING=true
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Changed from 80:80 to avoid conflict
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rest-api
    networks:
      - internal

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db  # Added persistent storage
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - internal

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo  # Added explicit dependency
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  node_modules:
  mongo_data:  # Added volume for MongoDB data persistence